=== KhaledAyman22/ITI/XML/Day1/demo/demo1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ITI (ITI-manager,ITI.vice-manager,copyrightsign)>
<!ELEMENT ITI-manager (#PCDATA)>
<!ELEMENT ITI.vice-manager (#PCDATA|ITI.SpecializedTracks|ITI.ScientificDept)*>
<!ATTLIST ITI.SpecializedTracks
name CDATA #REQUIRED
>
<!ELEMENT ITI.SpecializedTracks (ProgramManager,Track+)>

<!ELEMENT ProgramManager (#PCDATA)>
<!ATTLIST Track
mgr CDATA #IMPLIED>

<!ATTLIST ITI.ScientificDept
mgr CDATA #REQUIRED>

<!ATTLIST platform
mgr CDATA #IMPLIED>

<!ELEMENT Track (#PCDATA)>
<!ELEMENT platform (#PCDATA)>

<!ELEMENT copyrightsign EMPTY>
<!ELEMENT ITI.ScientificDept (platform+)>

=== KhaledAyman22/ITI/XML/Day1/demo/ITIhierachy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ITI SYSTEM "demo1.dtd">
<ITI>
	<ITI-manager>Dr.Heba Saleh</ITI-manager>
	<ITI.vice-manager>
	<ITI.SpecializedTracks name="Specialized Tracks">
	<ProgramManager>Eng.Bahaa</ProgramManager>
			<Track mgr="Eng.Dalia Rasmy">Short Training 
			</Track>
			<Track>Community Development Program
			</Track>
		</ITI.SpecializedTracks>
		Eng.Amr El Shafey
  <ITI.ScientificDept  mgr="Eng.Sherif Sharaf">
      <platform>System Development</platform>
			<platform mgr="Eng. Asmaa">Java</platform>
			<platform mgr="Eng. Shahinaz">ERP</platform>
			<platform mgr="Eng. Rania">UNIX</platform>
		</ITI.ScientificDept>
	</ITI.vice-manager>
<copyrightsign></copyrightsign>
</ITI>
